name: Build packages

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  ubuntupackage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      # - name: Build package
      #   id: build
      #   uses: ./.github/actions/build_ubuntu_package
      # - name: Test package
      #   uses: ./.github/actions/test_ubuntu_package
      #   with:
      #     package_file: ${{steps.build.outputs.package_file }}

      - name: Publish PPA
        uses: yuezk/publish-ppa-package@v1.0.0
        with:
          repository: 'ppa:bishwash369/espressoppa'
          gpg_private_key: ${{ secrets.ESPRESSO_PPA_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.ESPRESSO_PPA_PASSPHRASE }}
          pkgdir: '${{ github.workspace }}/artifacts/deb-build/globalprotect-openconnect*/'

          

